# Generated by Django 2.2.3 on 2019-09-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190915_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='add_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
